name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install swipl
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt-get install swi-prolog
    - uses: actions/checkout@v2
    - name: start xtdb
      run: docker run -d --pull=always -tip 6543:3000 ghcr.io/xtdb/xtdb-standalone-ea
    - name: wait for port
      run:  curl --retry 20 --retry-all-errors --retry-delay 5 http://localhost:6543/status
    - name: run tests
      run: for f in *.pl; do swipl -g run_tests -t halt $f; done
