name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install swipl
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt-get install swi-prolog
    - uses: actions/checkout@v2
    - name: start xtdb
      run: docker run -d --pull=always -tip 5432:5432 ghcr.io/xtdb/xtdb:nightly-20250627

    - name: build foreign library
      run: ./build.sh

    - name: wait for xtdb
      uses: iFaxity/wait-on-action@v1.2.1
      with:
        resource: tcp:localhost:5432
        timeout: 60000

    - name: run tests
      run: for f in *.pl; do swipl -p foreign=. -g run_tests -t halt $f; done
