name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      xtdb:
        image: ghcr.io/xtdb/xtdb:nightly-20250627
        ports:
          - 5433:5432

    steps:
    - name: install swipl
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends swi-prolog
    - uses: actions/checkout@v2

    - name: build foreign library
      run: ./build-debug.sh

    - name: run tests
      run: for f in *.pl; do swipl -p foreign=. -g run_tests -t halt $f; done
